### ISSUE TITLE
java.nio.file.FileSystemException: C:\Users\AppData\Local\Temp\kafka-8364428204801180638\version-2\log.1: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by ghost** [code-not-found/spring-kafka#6]
I've started the Zookeeper on as shown below

```
2018-12-16 12:20:58,109 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=C:\Users\e081155\AppData\Local\Temp\
2018-12-16 12:20:58,110 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
2018-12-16 12:20:58,113 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Windows 10
2018-12-16 12:20:58,116 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2018-12-16 12:20:58,117 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=10.0
2018-12-16 12:20:58,117 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=e081155
2018-12-16 12:20:58,118 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=C:\Users\e081155
2018-12-16 12:20:58,118 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=C:\Apache-Kafka\zookeeper-3.4.12\bin
2018-12-16 12:20:58,145 [myid:] - INFO  [main:ZooKeeperServer@835] - tickTime set to 2000
2018-12-16 12:20:58,145 [myid:] - INFO  [main:ZooKeeperServer@844] - minSessionTimeout set to -1
2018-12-16 12:20:58,147 [myid:] - INFO  [main:ZooKeeperServer@853] - maxSessionTimeout set to -1
2018-12-16 12:20:58,382 [myid:] - INFO  [main:ServerCnxnFactory@117] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
2018-12-16 12:20:58,384 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
```

I'm using Spring Boot version 2.1.1.RELEASE.

```
2018-12-16 12:21:13.672 ERROR 5976 --- [       Thread-1] org.apache.kafka.test.TestUtils          : Error deleting C:\Users\AppData\Local\Temp\kafka-8364428204801180638

java.nio.file.FileSystemException: C:\Users\AppData\Local\Temp\kafka-8364428204801180638\version-2\log.1: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_162]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_162]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_162]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source) ~[na:1.8.0_162]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[na:1.8.0_162]
	at java.nio.file.Files.delete(Unknown Source) ~[na:1.8.0_162]
	at org.apache.kafka.common.utils.Utils$2.visitFile(Utils.java:734) ~[kafka-clients-2.0.1.jar:na]
	at org.apache.kafka.common.utils.Utils$2.visitFile(Utils.java:723) ~[kafka-clients-2.0.1.jar:na]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[na:1.8.0_162]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[na:1.8.0_162]
	at org.apache.kafka.common.utils.Utils.delete(Utils.java:723) ~[kafka-clients-2.0.1.jar:na]
	at org.apache.kafka.test.TestUtils$1.run(TestUtils.java:184) ~[kafka-clients-2.0.0-test.jar:na]
```

**Comment by swapnil-kotwal-sp** [comment]
+1 same for me

**Comment by yakuninv** [comment]
+1

**Comment by wahidgazzah** [comment]
Hello,

I'm using Spring Boot version 2.1.8.RELEASE, and I have the same problem:

Have you a solution please ?

[Thread-2] ERROR o.a.k.t.TestUtils - Error deleting C:\Users\usr\AppData\Local\Temp\kafka-255644115154741962
java.nio.file.FileSystemException: C:\Users\usr\AppData\Local\Temp\kafka-255644115154741962\version-2\log.1: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.apache.kafka.common.utils.Utils$2.visitFile(Utils.java:734)
	at org.apache.kafka.common.utils.Utils$2.visitFile(Utils.java:723)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.apache.kafka.common.utils.Utils.delete(Utils.java:723)
	at org.apache.kafka.test.TestUtils$1.run(TestUtils.java:184)
